development:
  adapter: sqlite3
  database: database.db

test:
  adapter: sqlite3
  database: database.db

production:
  adapter: postgresql
  database: dfrneesl2i7opi
  username: absdxzqoyihdfn
  password: 9ea381314b0489246c55c87de5dd860d382899c67f6959ef2587e5ef4d652313
  host: ec2-3-89-0-52.compute-1.amazonaws.com